### ISSUE TITLE
Support options for `EXPIRE` command

### ISSUE THREAD

**Issue by olttwa** [taoensso/carmine#285]
Hey @ptaoussanis, Hope you are doing well! 👋 

I wanted to use an option with the EXPIRE command. Carmine's native `expire` function only supports 2 args: `key` & `seconds`. Would it be possible to add support for a variadic option `[NX | XX | GT | LT]`?

Thanks!

**Comment by ptaoussanis** [comment]
Hi there, please see [here](https://github.com/taoensso/carmine/wiki/1-Getting-started#command-coverage)

**Comment by olttwa** [comment]
Thanks @ptaoussanis. I'll use `redis-call` until options are supported in Carmine.

> On a side-note, can you double-check if Carmine's command generation from spec logic is correct?
Redis spec has specified optional conditions, and the same can be seen in `carmine-commands.edn` as well under `:fn-params-more [key seconds & args]`. However, `car/expire` only takes 2 args: `key` & `seconds`. 
The parser seems to be working correctly for other commands taking variadic number of args like `HSET`

**Comment by olttwa** [comment]
I updated Carmine from `3.1.0` to `3.3.0-RC1`, and the expire command has support for options in newer version.

Closing this issue, thanks.
