### ISSUE TITLE
car/with-new-pubsub-listener & and car/set in functions

### ISSUE THREAD

**Issue by matteoredaelli** [taoensso/carmine#286]
Hello

I can replicate correctly the sample about pub / sub with "println" but I cannot add a car/set in the listener function

```clojure
  (def listener
    (car/with-new-pubsub-listener my-conn-spec
      {
       "foo"  (fn f1
                [msg]
                (println msg)
                (car/set "a" "1")
                )
       "foo*"   (fn f2 [msg] (println "Pattern match: " msg))}
      (car/subscribe  queue-name)
      (car/psubscribe "foo*")
      ))
```

When I publish a sample message 

```bash
127.0.0.1:6379> PUBLISH foo c
(integer) 2
127.0.0.1:6379> get a
"2"

```

I get 

```bash
[subscribe foo 1]
Pattern match:  [psubscribe foo* 2]

[message foo c]
[pmessage foo* foo c]

```

I do not get any errors, but the value of the key "a" is not updated.

What's wrong with my code?

Thanks in advance
Matteo

**Comment by ptaoussanis** [comment]
@matteoredaelli Hi Matteo, `car/set` and other Redis commands need to be called within a `wcar` context.

The listener's connection context is intentionally separate. For example you may want the listener to receive messages from a particular connection, but send commands via a different connection.

Hope that helps!
