### ISSUE TITLE
Get / Set Data Type inconsistent

### ISSUE THREAD

**Issue by zerg000000** [taoensso/carmine#287]
Is it the expected behavior?

```clj
(car/wcar {} (car/set "a" 1))
(car/wcar {} (car/get "a"))
;; => "1"
;; set integer, but we get string back

(car/wcar {} (car/set "b" {:a 1}))
(car/wcar {} (car/get "b"))
;; => {:a 1}
;; set map, we get map as expected
```

**Comment by ptaoussanis** [comment]
@zerg000000 Hi Albert! Yes, that may seem a bit confusing but is expected behaviour.

Would recommend checking out the [Getting started](https://github.com/taoensso/carmine/wiki/1-Getting-started#serialization) guide.
