### ISSUE TITLE
Support commands in RediSearch, RedisJSON, RedisTimeSeries, RedisBloom

### ISSUE THREAD

**Issue by zerg000000** [taoensso/carmine#293]
Just curious about whether is there any interest in adding support to RediSearch, RedisJSON, RedisTimeSeries, RedisBloom?

**Comment by ptaoussanis** [comment]
@zerg000000 Hi Albert!

Carmine already supports arbitrary Redis commands (including commands for any installed modules) via the [redis-call](https://taoensso.github.io/carmine/taoensso.carmine.html#var-redis-call) command.

Hope that helps?

**Comment by ptaoussanis** [comment]
BTW I've just added a mention of Redis modules to the `redis-call` docstring to make it clearer that it's applicable there too 👍
