### ISSUE TITLE
Handling locked messages after JVM crash

### ISSUE THREAD

**Issue by marioaquino** [taoensso/carmine#294]
Do you have any advice for handling situations where messages are effectively locked indefinitely after a JVM crash?  The situation I'm describing is one where a worker has started processing a message event and the app where the worker is running crashes without graceful shutdown.

**Comment by ptaoussanis** [comment]
@marioaquino Hi Mario!

Could you please clarify some details?:

1. Are you talking about using Carmine's message queue feature?
2. What version of Carmine are you using?
3. What makes you believe that the message is "locked indefinitely"? That wouldn't be normal behaviour, Carmine's message queue [is fault tolerant](https://github.com/taoensso/carmine/wiki/3-Message-queue) - locks will automatically expire after some time (specified in the enqueue call) if a handler crashes.

**Comment by marioaquino** [comment]
@ptaoussanis Peter,

I think I was wrong in the preface of my question.  I am using the latest version of carmine and using the message_queue feature.  In my testing, I am indeed seeing messages picked up after crashing the JVM.  My concerns are addressed.  Thanks for the quick response!

**Comment by ptaoussanis** [comment]
No worries, thanks for the confirmation. Cheers! :-)
