### ISSUE TITLE
Carmine redis does not support to read from replicas

### ISSUE THREAD

**Issue by shahceg** [taoensso/carmine#312]
We are currently using the Carmine Redis client for our ElastiCache Redis cluster, which is configured in a single non-shared mode with Cluster Mode Disabled. In this setup, AWS provides separate reader and primary endpoints, allowing us to execute read and write operations based on these respective endpoints. However, we are planning to migrate to a sharded cluster configuration with Cluster Mode Enabled. In this mode, AWS only provides a single configuration endpoint, and we do not have control over instructing the client to use specific reader endpoints for read commands. Some Java Redis clients like Lettuce have built-in capabilities to automatically discover and utilize replica nodes for read operations. I want to understand if Carmine offers similar functionality to leverage replica nodes for read commands in a Cluster Mode Enabled setup. If not, I would like to explore the feasibility of adding such a feature to Carmine and gather insights on the effort required for its implementation.

Thoughts?

**Comment by ptaoussanis** [comment]
Hi there. Carmine doesn't currently have support for Redis Cluster or Sentinel, but these are potential items for my [long-term roadmap](https://www.taoensso.com/roadmap/vote).

I haven't committed to a timeline yet, likely won't be this year.

**Comment by shahceg** [comment]
Thanks for the details, so currently there are no way to enforce the client (like opts) to use read commands from replica node?

**Comment by ptaoussanis** [comment]
> so currently there are no way in carmine to enforce the client (like opts) to use read commands from replica node?

If you provide the replica node's details in your Carmine connection options - then Carmine will use that node for read and write commands. But in this case Carmine will just naively use the node without any understanding that it's a read replica, and without any automatic discovery.

It might not be too difficult to do basic discovery yourself, though that's something you'd need to experiment with to make sure.

**Comment by shahceg** [comment]
Agree, but the difficulty here is that AWS never offer the primary and reader node details for Clustering as we have more than one shards for cluster mode enabled. so it's hard for us to the discovery from our end.
I figured out that there is a command called "READONLY" https://redis.io/docs/latest/commands/readonly/ which i think supported in carmine as well. We can initiate this command first and then the subsequent reads will be using replicas under this connection.

https://repost.aws/knowledge-center/elasticache-redis-client-readonly

**Comment by ptaoussanis** [comment]
> Agree, but the difficulty here is that AWS never offer the primary and reader node details for Clustering as we have more than one shards for cluster mode enabled

I'm not familiar with what AWS is doing, but there may be Redis-level commands that can help.

> which i think supported in carmine as well

All commands supported by your Redis server [will be supported by Carmine](https://github.com/taoensso/carmine/wiki/1-Getting-started#command-coverage). If there's no built-in function, you can always use [`redis-call`](https://cljdoc.org/d/com.taoensso/carmine/CURRENT/api/taoensso.carmine#redis-call).

Hope that helps!

**Comment by shahceg** [comment]
Appreciate your quick response. Thanks

**Comment by alberttwong** [comment]
Does this mean that there is no automatic failover from master to replica?

**Comment by ptaoussanis** [comment]
@alberttwong Hi Albert. Carmine doesn't currently support [Redis Sentinel](https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/) or [Redis Cluster](https://redis.io/docs/latest/operate/oss_and_stack/management/scaling/).

It also has no other automatic failover, so if you're doing manual replication (without Sentinel or Cluster) - you'd need to handle failover yourself.

I have sketched out a Sentinel implementation for the next version of Carmine, but that unfortunately won't be ready for early testers until next year at least.

**Comment by alberttwong** [comment]
Tested with redi enterprise and redis cloud.  Replicas work.

**Comment by ptaoussanis** [comment]
Excellent, thank you!
